name: Build Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BrokenDreamCI: "true"   # 设置环境变量

    steps:
      - name: Print env
        run: echo "BrokenDreamCI is $BrokenDreamCI"

      - uses: actions/checkout@v5

      - name: Set JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Chmod execution permission
        run: chmod +x gradlew

      - name: Build apk
        run: ./gradlew assembleRelease

      # 上传所有生成的 APK 到 GitHub Releases
      - name: Release Upload Apk
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.tag_name }}
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}